language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    licenses:
        - android-sdk-license-.+

script:
   - cd cloudboost
   - pwd
   - chmod u+x /home/travis/build/CloudBoost/JavaSDK/gradlew.sh
   - chmod u+x /home/travis/build/CloudBoost/JavaSDK/gradlew
   - /home/travis/build/CloudBoost/JavaSDK/gradlew test --stacktrace

after_success:
   - /home/travis/build/CloudBoost/JavaSDK/gradlew bintrayUpload
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/   
env:
  global:
  - secure: $SECURE_KEY
